resources:
  jobs:
    dnks_dab_demo_sample_2_job:
      name: dnks_dab_demo_sample_2_job
      tasks:
        - task_key: dnks_dab_demo_sample_task
          job_cluster_key: dnks_dab_demo_2_cluster
          spark_python_task:
            python_file: ../notebooks/job.py
          libraries:
            - whl: ../dist/*.whl

      job_clusters:
        - job_cluster_key: dnks_dab_demo_2_cluster
          new_cluster:
            node_type_id: i3.xlarge
            num_workers: 0
            spark_version: 16.0.x-scala2.12
            spark_conf:
              "spark.databricks.cluster.profile": "singleNode"
              "spark.master": "local[*, 4]"
            custom_tags:
              "ResourceClass": "SingleNode"